# Generated by Django 3.0.7 on 2020-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('진행', '진행중인 안건'), ('종료', '종료된 안건'), ('보류', '보류된 안건')], max_length=200),
        ),
    ]
